################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
weight = 1

################ Spanish language ##################
[es]
languageName = "Español"
languageCode = "es"
weight = 2
